name: Docs

on:
  push:
    branches:
    - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  docs:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: Set up Pages
      uses: actions/configure-pages@v1
    - name: "Select the latest stable Xcode 14.1"
      uses: devbotsxyz/xcode-select@v1
      with:
        version: "14.1"
    - name: Generate Docs Using Docc plugin
      run: |
            swift package --allow-writing-to-directory ./public \
            generate-documentation --target ElegantAPI \
            --disable-indexing \
            --transform-for-static-hosting \
            --hosting-base-path amitsamant.in/ElegantAPI \
            --output-path ./public
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./public
        
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: docs

    steps:
    - name: Deploy Docs
      uses: actions/deploy-pages@v1
